name: first-action
on:
  push: 
    branches:
      - "master"
jobs:
  show-files-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: echo ${{ secrets.TESTING }}
