name: Production application update
on:
  pull_request:
  push:
    branches: 
      - prod
jobs:
  build-image-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Execute ansible playbook
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ansible-playbook /root/update-containers.yml
          host: ${{ secrets.SSH_HOST }}
          username: root
          privateKey: ${{ SSH_PRIVATE_KEY}}
      - name: Test if prod fails
        run: python test_prod.py