name: install-requirements
on: [push]
jobs:
  build-image-requirements:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: basic
          POSTGRES_DB: basic
          POSTGRES_USER: basic
    env:
      PG_DBNAME: basic
      PG_USER: basic
      PG_PASSWORD: basic
      PG_HOST: 0.0.0.0
      PG_PORT: 5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run migrations 
        run: python3 manage.py makemigrations && python3 manage.py migrate
      - name: Up server and test
        run: python3 manage.py runserver 0.0.0.0:8000 && python3 test.py
      